apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: match-network
  namespace: skills
spec:
  podSelector:
    matchLabels:
      type: match
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
        - port: 80
        - port: 53