kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 이름-rolebinding
  namespace: 네임스페이스
subjects:
- kind: User
  name: 역할-user
roleRef:
  kind: Role
  name: 역할
  apiGroup: rbac.authorization.k8s.io